[package]
name = "lut-cube"
version = "0.2.0"
edition = "2024"
description = ".cube files parser"
license-file = "LICENSE"
keywords = ["lut", "graphics", "cube", "3Dlut"]
repository = "https://github.com/yury/lut-cube"

[features]


[dependencies]


