[package]
name = "lut-cube"
version = "0.2.0"
edition = "2024"
description = ".cube files parser"
license-file = "LICENSE"
keywords = ["lut", "graphics", "cube", "3Dlut"]
repository = "https://github.com/yury/lut-cube"

[features]
simd = []
rayon = ["dep:rayon"]

[dependencies]
rayon = { version = "1.10", optional = true }

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "lut_cube"
harness = false

